name: Simple Echo Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  echo_hello_world:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Echo Hello World
        run: echo "Hello World"
